# The objective is to perform VSTESTV2 with RerunOptions

jobs:
- job: RunTest4
  displayName: 'Run Tests'
  pool: Default
  steps:      
  - task: VisualStudioTestPlatformInstaller@1
    displayName: 'Visual Studio Test Platform Installer'
    inputs:
      versionSelector: 'latestPreRelease'
  - task: VSTest@2
    inputs:  
      testSelector: 'testAssemblies'     
      testAssemblyVer2: |
          **\*FlakyTestProject*.dll
          !**\obj\
      rerunFailedTests: true
      searchFolder: '$(System.DefaultWorkingDirectory)\bin\Debug\'
      rerunFailedThreshold: 60
      rerunMaxAttempts: 3
      vsTestVersion: 'toolsInstaller'
